name: ci

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: Swatinem/rust-cache@v2
      - run: pnpm i
      - run: pnpm lint-check
      - run: pnpm build
      - run: ls -lh pkg
      - run: pnpm tsc
      - run: pnpm test
      - run: pnpm -C packages/app build
